variables:
  DOCKER_REPOSITORY: mendersoftware/mender-ci-tools

stages:
  - test
  - build
  - publish

include:
  - project: 'Northern.tech/Mender/mendertesting'
    file:
      - '.gitlab-ci-check-commits.yml'
      - '.gitlab-ci-check-license.yml'
      - '.gitlab-ci-check-docker-build.yml'
      - '.gitlab-ci-github-status-updates.yml'
