stages:
  - build
  - publish
  - deploy

include:
  - remote: "https://raw.githubusercontent.com/0lmi/mender-ci-workflows/master/templates/gitlab/mender-artifact-build.gitlab-ci.yml"
  - remote: "https://raw.githubusercontent.com/0lmi/mender-ci-workflows/master/templates/gitlab/mender-artifact-upload.gitlab-ci.yml"
  - remote: "https://raw.githubusercontent.com/0lmi/mender-ci-workflows/master/templates/gitlab/mender-deployment-create.gitlab-ci.yml"

#
# Builds Mender demo single-file artifact and stores '.mender' binary
# to MENDER_ARTIFACTS_FOLDER folder
#
build:mender:artifact:
  stage: build
  extends: .build:mender:artifact
  script:
    - echo /home/root/.ssh > dest_dir
    - echo authorized_keys > filename
    - echo key > authorized_keys
    - |
      mender-artifact write module-image \
        -T single-file \
        --device-type raspberrypi4 \
        -o ${MENDER_ARTIFACTS_FOLDER}/artifact.mender \
        -n updated-authorized_keys-1.0 \
        --software-name authorized_keys \
        --software-version 1.0 \
        -f dest_dir \
        -f filename \
        -f authorized_keys

#
# Uploads built artifact from MENDER_ARTIFACTS_FOLDER folder to Mender server
# on merge event to one of 'main' or 'production' branches
#
publish:mender:artifact:
  stage: publish
  extends: .upload:mender:artifact
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^(main|production)$/'

#
# Deploys to 'group-dev' devices group on merge event to 'main' branch
#
deploy:mender:artifact:dev:
  extends:
    - .create:mender:deployment
    - .generate:mender:deployment:name
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  variables:
    MENDER_DEPLOYMENT_GROUP: group-dev

#
# Deploys to 'group-prod' devices group on merge event to 'production' branch
#
deploy:mender:artifact:prod:
  extends:
    - .create:mender:deployment
    - .generate:mender:deployment:name
  rules:
    - if: '$CI_COMMIT_BRANCH == "production"'
  variables:
    MENDER_DEPLOYMENT_GROUP: group-prod

#
# Sets custome deployment name (optionally)
#
.generate:mender:deployment:name:
  stage: deploy
  before_script:
    - export MENDER_DEPLOYMENT_NAME="app_${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHORT_SHA}"
