#
# The example shows how to deploy a Mender artifact to a single device.
#
# 'MENDER_SERVER_ACCESS_TOKEN' secret is required to be set in GitLab repo settings
#

stages:
  - build
  - publish
  - deploy

include:
  - project: 'Northern.tech/Mender/mender-ci-workflows'
    file: 'templates/gitlab/mender-artifact-build.gitlab-ci.yml'
    ref: 'master'
  - project: 'Northern.tech/Mender/mender-ci-workflows'
    file: 'templates/gitlab/mender-artifact-upload.gitlab-ci.yml'
    ref: 'master'
  - project: 'Northern.tech/Mender/mender-ci-workflows'
    file: 'templates/gitlab/mender-deployment-create.gitlab-ci.yml'
    ref: 'master'

variables:
  MENDER_SERVER_URL: https://hosted.mender.io # Mender server URL
  MENDER_ARTIFACT_NAME: artifact.mender       # Mender Artifact file name in the `MENDER_ARTIFACTS_FOLDER` folder
  MENDER_RELEASE_NAME:  auth_keys-1.0         # The name of Mender release

#
# Builds Mender demo single-file artifact and stores '.mender' binary
# to MENDER_ARTIFACTS_FOLDER folder
#
mender:build:artifact:
  stage: build
  extends: .mender:build:artifact
  script:
    - echo /home/root/.ssh > dest_dir
    - echo authorized_keys > filename
    - echo key > authorized_keys
    - |
      mender-artifact write module-image \
        -T single-file \
        --device-type raspberrypi4 \
        -o ${MENDER_ARTIFACTS_FOLDER}/${MENDER_ARTIFACT_NAME} \
        -n ${MENDER_RELEASE_NAME} \
        --software-name authorized_keys \
        --software-version 1.0 \
        -f dest_dir \
        -f filename \
        -f authorized_keys

#
# Uploads built artifact ${MENDER_ARTIFACTS_FOLDER}/${MENDER_ARTIFACT_NAME} to
# Mender server on merge event to 'main' branch
#
mender:upload:artifact:
  stage: publish
  extends: .mender:upload:artifact
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

#
# Deploys to to a single device on merge event to 'main' branch
#
mender:create:deployment:
  stage: deploy
  extends: .mender:create:deployment
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  variables:
    MENDER_DEVICES_LIST: '["5ca6090ff3a8e90001206535"]' # `MENDER_DEVICES_LIST` variable defines list of Mender devices a deployment will be triggered to
  before_script:
    - MENDER_DEPLOYMENT_NAME="app_${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHORT_SHA}" # `MENDER_DEPLOYMENT_NAME` variable defines the name of Mender deployment
